// <auto-generated />
using System;
using FileConverter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileConverter.Data.Migrations
{
    [DbContext(typeof(FileConverterDbContext))]
    [Migration("20260113203846_Passwordhash")]
    partial class Passwordhash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileConverter.Data.Models.Conversion", b =>
                {
                    b.Property<Guid>("ConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("conversion_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("from_type");

                    b.Property<string>("InputFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("input_file_name");

                    b.Property<string>("InputPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("input_path");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("output_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("to_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("ConversionId")
                        .HasName("PK__Conversi__E4E07B3F8969CC21");

                    b.HasIndex("UserId");

                    b.ToTable("Conversions");
                });

            modelBuilder.Entity("FileConverter.Data.Models.MonthlyUsage", b =>
                {
                    b.Property<Guid>("MonthlyUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("monthly_usage_id");

                    b.Property<int>("ConversionsUsed")
                        .HasColumnType("int")
                        .HasColumnName("conversions_used");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("MonthlyUsageId")
                        .HasName("PK__MonthlyU__BFE86465821FB67E");

                    b.HasIndex(new[] { "UserId", "Year", "Month" }, "UQ_MonthlyUsage_User_Year_Month")
                        .IsUnique();

                    b.ToTable("MonthlyUsage");
                });

            modelBuilder.Entity("FileConverter.Data.Models.Plan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxConversionPerMonth")
                        .HasColumnType("int")
                        .HasColumnName("max_conversion_per_month");

                    b.Property<long>("MaxUploadBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_upload_bytes");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monthly_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("PlanId")
                        .HasName("PK__Plans__BE9F8F1D0E389267");

                    b.HasIndex(new[] { "Name" }, "UQ_Plans_Name")
                        .IsUnique();

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("FileConverter.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370FBAE22FAA");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FileConverter.Data.Models.UserPlan", b =>
                {
                    b.Property<Guid>("UserPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_plan_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("UserPlanId")
                        .HasName("PK__UserPlan__7E75D75BB299C1AC");

                    b.HasIndex("PlanId");

                    b.HasIndex(new[] { "UserId" }, "UQ_UserPlan_User")
                        .IsUnique();

                    b.ToTable("UserPlan");
                });

            modelBuilder.Entity("FileConverter.Data.Models.Conversion", b =>
                {
                    b.HasOne("FileConverter.Data.Models.User", "User")
                        .WithMany("Conversions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Conversions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FileConverter.Data.Models.MonthlyUsage", b =>
                {
                    b.HasOne("FileConverter.Data.Models.User", "User")
                        .WithMany("MonthlyUsages")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MonthlyUsage_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FileConverter.Data.Models.UserPlan", b =>
                {
                    b.HasOne("FileConverter.Data.Models.Plan", "Plan")
                        .WithMany("UserPlans")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPlan_Plans");

                    b.HasOne("FileConverter.Data.Models.User", "User")
                        .WithOne("UserPlan")
                        .HasForeignKey("FileConverter.Data.Models.UserPlan", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPlan_Users");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FileConverter.Data.Models.Plan", b =>
                {
                    b.Navigation("UserPlans");
                });

            modelBuilder.Entity("FileConverter.Data.Models.User", b =>
                {
                    b.Navigation("Conversions");

                    b.Navigation("MonthlyUsages");

                    b.Navigation("UserPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
